workflows:
  android-workflow:
    name: Spatial Shell APK
    max_build_duration: 30
    environment:
      java: 17

    scripts:
      - name: Go to Android directory
        script: |
          cd android
          ls -la

      - name: Make gradlew executable
        script: |
          chmod +x gradlew
          ls -la gradlew

      - name: Build Debug APK
        script: |
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/**/*.apk
