workflows:
  android-workflow:
    name: Android APK
    max_build_duration: 30
    environment:
      java: 17
    scripts:
      - name: Build APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
