workflows:
  android-workflow:
    name: Spatial Shell APK
    max_build_duration: 30
    environment:
      java: 17
    scripts:
      - name: Make gradlew executable
        script: chmod +x gradlew

      - name: Build Debug APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
