#!/usr/bin/env sh

##############################################################################
##  Gradle start up script for POSIX generated by Gradle.
##############################################################################

DIR="$(cd "$(dirname "$0")" && pwd)"
APP_HOME="$DIR"
APP_NAME="Gradle"
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

exec "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" "$@"
